"""
## PANDAS - JOIN / MERGE AND CONCATENATION

 merge()
-------
Used to combine DataFrames using a common column/key.

concat()
--------
Used to combine multiple Pandas objects along rows or columns.

Important merge types:
- inner
- left
- right
- outer
"""

In [1]:
import pandas as pd

In [3]:
customers = {
    "Customer_ID": [101, 102, 103, 104],
    "Name": ["Amit", "Sneha", "Rahul", "Priya"],
    "City": ["Pune", "Mumbai", "Delhi", "Nashik"]
}

In [4]:
orders = {
    "Customer_ID": [101, 102, 103, 105],
    "Product": ["Laptop", "Phone", "Tablet", "Monitor"],
    "Amount": [65000, 42000, 30000, 18000]
}

In [5]:
customers_df = pd.DataFrame(customers)
orders_df = pd.DataFrame(orders)

In [6]:
print("\ncustomers_Table")
customers_df

customers_Table

   Customer_ID   Name    City
0          101   Amit    Pune
1          102  Sneha  Mumbai
2          103  Rahul   Delhi
3          104  Priya  Nashik

In [7]:
print("\norders_df")
orders_df

orders_df

   Customer_ID  Product  Amount
0          101   Laptop   65000
1          102    Phone   42000
2          103   Tablet   30000
3          105  Monitor   18000

PART 1: MERGE

In [8]:
# Inner Merge
inner_merge = pd.merge(
    customers_df,
    orders_df,
    on="Customer_ID",
    how="inner"
)

print("INNER MERGE:")
print(inner_merge)

INNER MERGE:
   Customer_ID   Name    City Product  Amount
0          101   Amit    Pune  Laptop   65000
1          102  Sneha  Mumbai   Phone   42000
2          103  Rahul   Delhi  Tablet   30000

In [9]:
# Left Merge
left_merge = pd.merge(
    customers_df,
    orders_df,
    on="Customer_ID",
    how="left"
)

print("\nLEFT MERGE:")
print(left_merge)

LEFT MERGE:
   Customer_ID   Name    City Product   Amount
0          101   Amit    Pune  Laptop  65000.0
1          102  Sneha  Mumbai   Phone  42000.0
2          103  Rahul   Delhi  Tablet  30000.0
3          104  Priya  Nashik     NaN      NaN

In [10]:
# Outer Merge
outer_merge = pd.merge(
    customers_df,
    orders_df,
    on="Customer_ID",
    how="outer"
)

print("\nOUTER MERGE:")
print(outer_merge)

OUTER MERGE:
   Customer_ID   Name    City  Product   Amount
0          101   Amit    Pune   Laptop  65000.0
1          102  Sneha  Mumbai    Phone  42000.0
2          103  Rahul   Delhi   Tablet  30000.0
3          104  Priya  Nashik      NaN      NaN
4          105    NaN     NaN  Monitor  18000.0

PART 2: CONCAT :

In [11]:
january = pd.DataFrame({
    "Product": ["Laptop", "Phone", "Mouse"],
    "Sales": [50000, 30000, 5000]
})

february = pd.DataFrame({
    "Product": ["Laptop", "Phone", "Mouse"],
    "Sales": [60000, 35000, 7000]
})